[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
cache_path = "cache_forge"
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 1
via_ir = true
bytecode_hash = "none"

remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

[rpc_endpoints]
monad = "${MONAD_RPC_URL}"
monad-testnet = "https://testnet-rpc.monad.xyz"
